### ISSUE TITLE
Design der GUI

### ISSUE THREAD

**Issue by cewol101** [ProPra16/programmierpraktikum-abschlussprojekt-nofuture-1#4]
## GUI Design aufmotzen

Design ist im schlichten grau gehalten
css wieder aktivieren und dem Programm Farbe und leben einhauchen

Kreativität ist keine Grenzen gesetzt.

Einzige Vorgabe:
### KEIN PINK

**Comment by Anabr101** [comment]
ohne **Pink** ohne mich  :disappointed: :cry: 

:smile:  na gut aber nur für euch :heart_decoration:

**Comment by cewol101** [comment]
Kannst ja auch schauen, ob es sinnvoll erscheint einen ProgressBar hinzuzufügen
