### ISSUE TITLE
Akzeptanztest Zyklus fertigstellen

### ISSUE THREAD

**Issue by cewol101** [ProPra16/programmierpraktikum-abschlussprojekt-nofuture-1#6]
- Akzeptanztest soll Farbe von Rot auf Grün sobald alle Tests davon funktionieren
- Zurück Button erzeugen, falls Akzeptanztest verändert werden soll
- Codeskelett für Akzeptanztest implementieren

**Comment by Giga-Phlips-Phlops** [comment]
Ist das jetzt deine aufgabe? unsere?

**Comment by cewol101** [comment]
Ich dachte du hättest ja genug, deswegen nahm ich das als meine Aufgabe an?
